/* Generated by Nim Compiler v1.0.2 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/local/stow/nim/lib -I'/home/yoxem/桌面/tshunhue/BigNumOperationNim/連結' -o /home/yoxem/.cache/nim/fib_d/@mfib.nim.c.o /home/yoxem/.cache/nim/fib_d/@mfib.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tySequence__U48dCdy0noze9bNL2psZZGA tySequence__U48dCdy0noze9bNL2psZZGA;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA tySequence__9bAGqSvkAaFL9bWjsEPslrFA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct HugeNum HugeNum;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct HugeNum {
NIM_BOOL Field0;
tySequence__U48dCdy0noze9bNL2psZZGA* Field1;
};
struct tySequence__U48dCdy0noze9bNL2psZZGA {
  TGenericSeq Sup;
  unsigned int data[SEQ_DECL_SIZE];
};
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA {
  TGenericSeq Sup;
  NU32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(int, fib)(int a);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(tySequence__U48dCdy0noze9bNL2psZZGA*, get_seq2)(void);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_NIMCALL(void, Marker_tySequence__U48dCdy0noze9bNL2psZZGA)(void* p, NI op);
N_CDECL(void, example)(HugeNum* Result);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, fibDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI__EfDYb5NOiMBijiUDCmXqPw_;
TNimType NTI__U48dCdy0noze9bNL2psZZGA_;
NIM_CONST struct {
  TGenericSeq Sup;
  NU32 data[1];
} TM__xgSOGG8fvQlwPH9bPyp9bbTg_6 = {{1, 1 | NIM_STRLIT_FLAG}, {((NU32) 9)}};
NIM_CONST tySequence__9bAGqSvkAaFL9bWjsEPslrFA* TM__xgSOGG8fvQlwPH9bPyp9bbTg_5 = ((tySequence__9bAGqSvkAaFL9bWjsEPslrFA*)&TM__xgSOGG8fvQlwPH9bPyp9bbTg_6);
NIM_CONST struct {
  TGenericSeq Sup;
  unsigned int data[2];
} TM__xgSOGG8fvQlwPH9bPyp9bbTg_8 = {{2, 2 | NIM_STRLIT_FLAG}, {((NU32) 32),
((NU32) 12)}};
NIM_CONST tySequence__U48dCdy0noze9bNL2psZZGA* TM__xgSOGG8fvQlwPH9bPyp9bbTg_7 = ((tySequence__U48dCdy0noze9bNL2psZZGA*)&TM__xgSOGG8fvQlwPH9bPyp9bbTg_8);
static N_INLINE(NI, subInt)(NI a, NI b) {	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, addInt)(NI a, NI b) {	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s) {	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA9_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA9_: ;
}
static N_INLINE(void, popFrame)(void) {	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_NIMCALL(int, fib)(int a) {	int result;
	nimfr_("fib", "/home/yoxem/\346\241\214\351\235\242/tshunhue/BigNumOperationNim/\351\200\243\347\265\220/fib.nim");
{	result = (int)0;
	nimln_(8, "/home/yoxem/\346\241\214\351\235\242/tshunhue/BigNumOperationNim/\351\200\243\347\265\220/fib.nim");
	{
		if (!(a <= ((NI32) 2))) goto LA3_;
		nimln_(9, "/home/yoxem/\346\241\214\351\235\242/tshunhue/BigNumOperationNim/\351\200\243\347\265\220/fib.nim");
		result = ((int) 1);
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM__xgSOGG8fvQlwPH9bPyp9bbTg_2;
		int T6_;
		NI TM__xgSOGG8fvQlwPH9bPyp9bbTg_3;
		int T7_;
		NI TM__xgSOGG8fvQlwPH9bPyp9bbTg_4;
		nimln_(11, "/home/yoxem/\346\241\214\351\235\242/tshunhue/BigNumOperationNim/\351\200\243\347\265\220/fib.nim");
		TM__xgSOGG8fvQlwPH9bPyp9bbTg_2 = subInt(a, ((NI32) 1));
		if (TM__xgSOGG8fvQlwPH9bPyp9bbTg_2 < (-2147483647 -1) || TM__xgSOGG8fvQlwPH9bPyp9bbTg_2 > 2147483647) raiseOverflow();
		T6_ = (int)0;
		T6_ = fib((NI32)(TM__xgSOGG8fvQlwPH9bPyp9bbTg_2));
		TM__xgSOGG8fvQlwPH9bPyp9bbTg_3 = subInt(a, ((NI32) 2));
		if (TM__xgSOGG8fvQlwPH9bPyp9bbTg_3 < (-2147483647 -1) || TM__xgSOGG8fvQlwPH9bPyp9bbTg_3 > 2147483647) raiseOverflow();
		T7_ = (int)0;
		T7_ = fib((NI32)(TM__xgSOGG8fvQlwPH9bPyp9bbTg_3));
		TM__xgSOGG8fvQlwPH9bPyp9bbTg_4 = addInt(T6_, T7_);
		if (TM__xgSOGG8fvQlwPH9bPyp9bbTg_4 < (-2147483647 -1) || TM__xgSOGG8fvQlwPH9bPyp9bbTg_4 > 2147483647) raiseOverflow();
		result = (NI32)(TM__xgSOGG8fvQlwPH9bPyp9bbTg_4);
	}
	LA1_: ;
	nimln_(12, "/home/yoxem/\346\241\214\351\235\242/tshunhue/BigNumOperationNim/\351\200\243\347\265\220/fib.nim");
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence__U48dCdy0noze9bNL2psZZGA)(void* p, NI op) {
	tySequence__U48dCdy0noze9bNL2psZZGA* a;
	NI T1_;
	a = (tySequence__U48dCdy0noze9bNL2psZZGA*)p;
	T1_ = (NI)0;
}
N_NIMCALL(tySequence__U48dCdy0noze9bNL2psZZGA*, get_seq2)(void) {	tySequence__U48dCdy0noze9bNL2psZZGA* result;
	tySequence__U48dCdy0noze9bNL2psZZGA* s;
	nimfr_("get_seq2", "/home/yoxem/\346\241\214\351\235\242/tshunhue/BigNumOperationNim/\351\200\243\347\265\220/fib.nim");
{	result = (tySequence__U48dCdy0noze9bNL2psZZGA*)0;
	nimln_(15, "/home/yoxem/\346\241\214\351\235\242/tshunhue/BigNumOperationNim/\351\200\243\347\265\220/fib.nim");
	genericSeqAssign((&s), TM__xgSOGG8fvQlwPH9bPyp9bbTg_5, (&NTI__U48dCdy0noze9bNL2psZZGA_));
	nimln_(16, "/home/yoxem/\346\241\214\351\235\242/tshunhue/BigNumOperationNim/\351\200\243\347\265\220/fib.nim");
	genericSeqAssign((&result), s, (&NTI__U48dCdy0noze9bNL2psZZGA_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}
N_CDECL(void, example)(HugeNum* Result) {	HugeNum s;
	NIM_BOOL colontmp_;
	tySequence__U48dCdy0noze9bNL2psZZGA* colontmp__2;
	nimfr_("example", "/home/yoxem/\346\241\214\351\235\242/tshunhue/BigNumOperationNim/\351\200\243\347\265\220/fib.nim");
{	nimZeroMem((void*)(&s), sizeof(HugeNum));
	nimln_(20, "/home/yoxem/\346\241\214\351\235\242/tshunhue/BigNumOperationNim/\351\200\243\347\265\220/fib.nim");
	colontmp_ = NIM_TRUE;
	nimln_(21, "/home/yoxem/\346\241\214\351\235\242/tshunhue/BigNumOperationNim/\351\200\243\347\265\220/fib.nim");
	genericSeqAssign((&colontmp__2), TM__xgSOGG8fvQlwPH9bPyp9bbTg_7, (&NTI__U48dCdy0noze9bNL2psZZGA_));
	nimln_(20, "/home/yoxem/\346\241\214\351\235\242/tshunhue/BigNumOperationNim/\351\200\243\347\265\220/fib.nim");
	s.Field0 = colontmp_;
	genericSeqAssign((&s.Field1), colontmp__2, (&NTI__U48dCdy0noze9bNL2psZZGA_));
	nimln_(23, "/home/yoxem/\346\241\214\351\235\242/tshunhue/BigNumOperationNim/\351\200\243\347\265\220/fib.nim");
	(*Result).Field0 = s.Field0;
	genericSeqAssign((&(*Result).Field1), s.Field1, (&NTI__U48dCdy0noze9bNL2psZZGA_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, initStackBottomWith)(void* locals) {	nimGC_setStackBottom(locals);
}

void PreMainInner(void) {
}

int cmdCount;
char** cmdLine;
char** gEnv;
void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	systemDatInit000();
	initStackBottomWith((void *)&inner);
	systemInit000();
	fibDatInit000();
	(*inner)();
}

N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

N_LIB_PRIVATE N_NIMCALL(void, fibDatInit000)(void) {
NTI__U48dCdy0noze9bNL2psZZGA_.size = sizeof(tySequence__U48dCdy0noze9bNL2psZZGA*);
NTI__U48dCdy0noze9bNL2psZZGA_.kind = 24;
NTI__U48dCdy0noze9bNL2psZZGA_.base = (&NTI__EfDYb5NOiMBijiUDCmXqPw_);
NTI__U48dCdy0noze9bNL2psZZGA_.flags = 2;
NTI__U48dCdy0noze9bNL2psZZGA_.marker = Marker_tySequence__U48dCdy0noze9bNL2psZZGA;
}

