/* Generated by Nim Compiler v1.0.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
#ifndef __fib__
#define __fib__
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__U48dCdy0noze9bNL2psZZGA tySequence__U48dCdy0noze9bNL2psZZGA;
typedef struct TGenericSeq TGenericSeq;
typedef struct HugeNum HugeNum;
struct TGenericSeq {
NI len;
NI reserved;
};
struct tySequence__U48dCdy0noze9bNL2psZZGA {
  TGenericSeq Sup;
  unsigned int data[SEQ_DECL_SIZE];
};
N_NOCONV(void, signalHandler)(int sign);
N_NIMCALL(NI, getRefcount)(void* p);
N_NIMCALL(int, fib)(int a);
N_NIMCALL(tySequence__U48dCdy0noze9bNL2psZZGA*, get_seq2)(void);
N_CDECL(void, example)(HugeNum* Result);
N_CDECL(void, NimMain)(void);
#endif /* __fib__ */
